# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Youtube_Downloader_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time
import Youtube_Downloader as yd

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(290, 154)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(10, 10, 261, 20))
        self.url.setObjectName("url")
        
        self.download_Button = QtWidgets.QPushButton(self.centralwidget)
        self.download_Button.setGeometry(QtCore.QRect(200, 50, 75, 23))
        self.download_Button.setObjectName("download_Button")
        #self.download_Button.clicked.connect(lambda: self.output(self.url.text()))
        self.download_Button.clicked.connect(lambda: self.option(self.url.text()))
        #self.download_Button.setEnabled(self.check_input(self.url.text()))
        
        self.single_audio_check_button = QtWidgets.QRadioButton(self.centralwidget)
        self.single_audio_check_button.setGeometry(QtCore.QRect(100, 60, 82, 17))
        self.single_audio_check_button.setObjectName("single_audio_check_button")
        
        self.single_video_check_button = QtWidgets.QRadioButton(self.centralwidget)
        self.single_video_check_button.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.single_video_check_button.setObjectName("single_video_check_button")
        
        self.playlist_audio_check_button = QtWidgets.QRadioButton(self.centralwidget)
        self.playlist_audio_check_button.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.playlist_audio_check_button.setObjectName("playlist_audio_check_button")
        
        self.playlist_video_check_button = QtWidgets.QRadioButton(self.centralwidget)
        self.playlist_video_check_button.setGeometry(QtCore.QRect(100, 40, 82, 17))
        self.playlist_video_check_button.setObjectName("playlist_video_check_button")
        
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(110, 90, 47, 13))
        self.output_label.setObjectName("output_label")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 290, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.download_Button.setText(_translate("MainWindow", u"Download", None))
        self.download_Button.setShortcut(_translate("MainWindow", u"Return", None))
        self.single_audio_check_button.setText(_translate("MainWindow", "Single Audio"))
        self.single_video_check_button.setText(_translate("MainWindow", "Single Video"))
        self.playlist_audio_check_button.setText(_translate("MainWindow", "Playlist Audio"))
        self.playlist_video_check_button.setText(_translate("MainWindow", "Playlist Video"))
        self.output_label.setText(_translate("MainWindow", "TextLabel"))
        self.url.setPlaceholderText(_translate("MainWindow", u"URL:", None))

    def output(self,text):
        self.output_label.setText(text)
        self.output_label.adjustSize()
        
    def option(self,url):
    
        if self.single_audio_check_button.isChecked():
            self.output_label.setText("Downloading Single Audio")
            self.output_label.adjustSize()
            time.sleep(2)
            yd.single_audio(url)
            self.output_label.setText("Download Complete")
            self.output_label.adjustSize()
            
        elif self.single_video_check_button.isChecked():
            self.output_label.setText("Downloading Single Video")
            self.output_label.adjustSize()
            yd.single_video(url)
            self.output_label.setText("Download Complete")
            self.output_label.adjustSize()
            
        elif self.playlist_video_check_button.isChecked():
            self.output_label.setText("Downloading Playlist Audio")
            self.output_label.adjustSize()
            
            yd.video_playlist(url)
            self.output_label.setText("Download Complete")
            self.output_label.adjustSize()
            
        elif self.playlist_audio_check_button.isChecked():
            self.output_label.setText("Downloading Playlist Video")
            self.output_label.adjustSize()
            yd.audio_playlist(url)
            self.output_label.setText("Download Complete")
            self.output_label.adjustSize()
            
        else:
            self.output_label.setText("Input URL")
            self.output_label.adjustSize()
    
    def check_input(self, txt):
        if txt == "":
            return False
        else:
            return True
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    #open qss file
    File = open("Style.qss",'r')
    with File:
        qss = File.read()
        app.setStyleSheet(qss)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
